Release 0.0.1
teamgantt/expo-release-config pull request #2
Opened 2019-08-22 16:52 UTC by bradbumbalough

Refactored the way the cli will work. Now, a single configuration file will contain the app schemes and version object.

Commands are:
- `expo-config generate [scheme]`
- `expo-config version [type] [--commit]

2019-08-26 13:28 UTC, brianium commented
@bradbumbalough I removed myself for now - until the time is right. It's an OCD thing. Feel free to assign/ping me when this bad brother is ready for review FOR REAL 🤝

2019-08-26 19:16 UTC, bradbyte commented
@brianium this should be good to go now. I had to make a tweak when when wiring it into our mobile CI.

2019-08-28 12:47 UTC, brianium commented on .circleci/config.yml
> +      jobs:
Curious why you opted for separate jobs for lint + test?

2019-08-28 12:47 UTC, brianium commented on .circleci/config.yml
> +          - test
What is this some lawless land of no newlines?

2019-08-28 12:48 UTC, brianium commented on .eslintrc.json
> +}
....it must be

2019-08-28 12:51 UTC, bradbyte commented on .eslintrc.json
> +}
:man_facepalming:

2019-08-28 12:53 UTC, bradbyte commented on .circleci/config.yml
> +      jobs:
Not really a reason... I could combine this.

2019-08-28 13:09 UTC, brianium requested changes
This looks good to me. A couple of simple new line things and one request for prettier + eslint. The lint stuff could probably wait, but it would be nice to drive at a simple/consistent way to handle formatting + linting.

I think the real test for this stuff is going to see it integrating in the mobile repo.

2019-08-28 13:09 UTC, brianium commented on .eslintrc.json
> +}
@tysonnero had a pretty cool integration of eslint and prettier in the [desktop app](https://github.com/teamgantt/timer/pull/1/files#diff-89e58816774d9ea132d8a0a652f3ad5aR22). Might be worth looking at [integrating prettier with eslint](https://prettier.io/docs/en/integrating-with-linters.html).

2019-08-28 13:11 UTC, brianium commented on .circleci/config.yml
> +      jobs:
I don't think I care that much. It has been a minute since I have looked at the circle ui. I just remember workflows added a bit of complexity - i.e restarting jobs instead of the entire build. Maybe they have fixed this 🤷‍♂ - a job per task seems overkill to me but maybe I am just 👴

2019-08-28 13:42 UTC, bradbyte commented
@brianium made some changes... thanks for the feedback!

2019-08-28 14:30 UTC, brianium approved these changes

2019-08-28 14:31 UTC, merged